using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
namespace Problem002
{
    class Program
    {
        static void Main(string[] args)
        {
            
            Console.WriteLine("sum + " + CalcSum().ToString());

            Console.Read();
        }

        static int CalcSum()
        {
            int sum = 0;
            int ultimo = 2;
            int penultimo = 1;
            int aux = 0;
            sum = ultimo;

            bool bContinue = true;

            while (bContinue)
            {
                aux = ultimo + penultimo;
                penultimo = ultimo;
                ultimo = aux;

                if (ultimo < 4000000)
                {
                    if (ultimo % 2 == 0)
                        sum += ultimo;
                }
                else
                    bContinue = false;
            }
            return sum;
        }
    }
}


